name: Publish Docker Image

on:
  push:
    branches:
      - 'main'
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push Docker image for ARM64
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          push: false
          file: docker/Dockerfile.arm64
          tags: |
            discuit/discuit:latest-arm64
            discuit/discuit:${{ github.sha }}-arm64

      # - name: Build for ARM64
      #   run: |
      #     docker buildx build --platform linux/arm64 --load -f docker/Dockerfile.arm64 -t discuit/discuit:arm64 .

      # - name: Build for AMD64
      #   run: |
      #     docker buildx build --platform linux/amd64 --load -f docker/Dockerfile.amd64 -t discuit/discuit:amd64 .

      # - name: Create and push Docker manifest
      #   run: |
      #     docker manifest create discuit/discuit:latest --amend discuit/discuit:arm64 --amend discuit/discuit:amd64
      #     docker manifest push discuit/discuit:latest

      - name: Create and push Docker manifest
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            discuit/discuit:latest
          sources: |
            discuit/discuit:arm64